stages:
  train:
    deps:
    - data/population.csv
    - train/regression.R
    cmd: Rscript train/regression.R
    params:
    - train.modeltype
    outs:
    - models/model.RDS
    metrics:
    - metrics/metrics.json
    plots:
    - plots/fit.png
